name: dart_vorbis
description: Dart bindings for libvorbisfile
version: 1.0.0
repository: https://github.com/the-byte-bender/dart_vorbis
ffigen:
  name: 'VorbisfileBindings'
  description: 'Bindings to libvorbisfile'
  output: 'lib/src/vorbisfile_generated_bindings.dart'
  preamble: |
    // ignore_for_file: always_specify_types, unused_element, unused_field
    // ignore_for_file: camel_case_types
    // ignore_for_file: non_constant_identifier_names
  headers:
    entry-points:
      - 'headers/codec.h'
      - 'headers/vorbisfile.h'
  functions:
    leaf:
      include:
        - '.*'
    expose-typedefs:
      include:
        - '.*'
environment:
  sdk: ^3.2.2

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.0

dev_dependencies:
  ffigen: ^10.0.0
  lints: ^2.1.0
  test: ^1.24.0
